In [1]:
import pandas as pd

In [2]:
airport_combined_path = '/content/drive/MyDrive/UTS SEM 3/MLAA/AT3/all_airports.csv'

In [3]:
airport_df = pd.read_csv(airport_combined_path)

In [4]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [5]:
airport_df['startingAirport'].unique()

array(['ATL', 'BOS', 'CLT', 'DEN', 'DFW', 'DTW', 'EWR', 'IAD', 'JFK',
       'LAX', 'LGA', 'MIA', 'OAK', 'ORD', 'PHL', 'SFO'], dtype=object)

In [6]:
airport_df.sample(10)

,legId,searchDate,flightDate,startingAirport,destinationAirport,travelDuration,isBasicEconomy,isRefundable,isNonStop,totalFare,totalTravelDistance,segmentsDepartureTimeEpochSeconds,segmentsDepartureTimeRaw,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
2552810,52254c8530047864a188528845bea768,2022-05-09,2022-05-28,CLT,SFO,PT8H30M,False,False,False,521.09,2753.0,1653746400||1653755700,2022-05-28T10:00:00.000-04:00||2022-05-28T12:3...,1653751980||1653777000,2022-05-28T11:33:00.000-04:00||2022-05-28T15:3...,IAD||SFO,CLT||IAD,United||United,UA||UA,Embraer 170||Boeing 737 MAX 9,5580||21300,327||2426,coach||coach
642740,4f94cc8569d2bce3527c524adce67e5f,2022-05-07,2022-05-24,ATL,DFW,PT2H32M,False,False,True,202.60,725.0,1653430920,2022-05-24T18:22:00.000-04:00,1653440040,2022-05-24T19:54:00.000-05:00,DFW,ATL,American Airlines,AA,Airbus A321,9120,725,coach
5096133,dece9b84d1b4a16996e583ce1bfc0f9c,2022-05-18,2022-05-20,DTW,SFO,PT9H48M,False,False,False,577.60,2324.0,1653076800||1653107400,2022-05-20T16:00:00.000-04:00||2022-05-20T21:3...,1653094860||1653112080,2022-05-20T18:01:00.000-07:00||2022-05-20T22:4...,LAX||SFO,DTW||LAX,Delta||Delta,DL||DL,Airbus A321||Embraer 175 (Enhanced Winglets),18060||4680,1985||339,coach||coach
11477083,f6516d62181624b382ec825a24a0fa25,2022-05-05,2022-05-06,ORD,IAD,PT1H46M,False,False,True,388.60,594.0,1651844400,2022-05-06T08:40:00.000-05:00,1651850760,2022-05-06T11:26:00.000-04:00,IAD,ORD,United,UA,Airbus A320,6360,594,coach
8124434,e0e4638007ea953afae81ff691d6be56,2022-05-07,2022-06-12,LAX,PHL,PT10H48M,False,False,False,721.19,2417.0,1655055780||1655087160,2022-06-12T10:43:00.000-07:00||2022-06-12T21:2...,1655070540||1655094660,2022-06-12T16:49:00.000-05:00||2022-06-13T00:3...,ORD||PHL,LAX||ORD,United||United,UA||UA,Boeing 757-300||Boeing 737-900,14760||7500,1745||672,coach||coach
187298,967bb9da12aa6a6ac7cd1d528ad81810,2022-04-22,2022-06-10,ATL,DTW,PT7H33M,False,False,False,206.61,1247.0,1654856040||1654876200,2022-06-10T06:14:00.000-04:00||2022-06-10T11:5...,1654864200||1654883220,2022-06-10T08:30:00.000-04:00||2022-06-10T13:4...,LGA||DTW,ATL||LGA,American Airlines||American Airlines,AA||AA,Embraer 170||Embraer 175,8160||7020,762||485,coach||coach
11790883,ae0925ac89d04b357a90bb62d817bcc0,2022-04-16,2022-04-26,PHL,DTW,PT10H7M,False,False,False,347.58,NaN,1650977700||1651004760,2022-04-26T08:55:00.000-04:00||2022-04-26T16:2...,1650986940||1651014120,2022-04-26T11:29:00.000-04:00||2022-04-26T19:0...,MCO||DTW,PHL||MCO,Spirit Airlines||Spirit Airlines,NK||NK,AIRBUS INDUSTRIE A321 SHARKLETS||Airbus A319,9240||9360,None||None,coach||coach
7207101,d867ec71f6751230be6a4e0e150a15ff,2022-04-18,2022-05-23,LAX,DTW,PT10H37M,False,False,False,229.58,NaN,1653366000||1653393300,2022-05-23T21:20:00.000-07:00||2022-05-24T07:5...,1653383580||1653404220,2022-05-24T05:13:00.000-04:00||2022-05-24T10:5...,FLL||DTW,LAX||FLL,Spirit Airlines||Spirit Airlines,NK||NK,||AIRBUS INDUSTRIE A320 SHARKLETS,17580||10920,None||None,coach||coach
10829008,526ad5116edd95610985fd8278c236ca,2022-05-12,2022-06-17,OAK,DFW,PT9H34M,False,False,False,224.58,NaN,1655492400||1655516640,2022-06-17T12:00:00.000-07:00||2022-06-17T18:4...,1655498040||1655526840,2022-06-17T13:34:00.000-07:00||2022-06-17T23:3...,LAS||DFW,OAK||LAS,Spirit Airlines||Spirit Airlines,NK||NK,||AIRBUS INDUSTRIE A321 SHARKLETS,5640||10200,None||None,coach||coach
7846332,e2aee1c45272fa6dc0f54834dec73d48,2022-05-02,2022-05-25,LAX,IAD,PT4H54M,False,False,True,398.60,2295.0,1653500520,2022-05-25T10:42:00.000-07:00,1653518160,2022-05-25T18:36:00.000-04:00,IAD,LAX,United,UA,Boeing 737 MAX 9,17640,2295,coach

In [7]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [8]:
airport_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13519999 entries, 0 to 13519998
Data columns (total 23 columns):
 #   Column                             Dtype
---  ------                             -----
 0   legId                              object
 1   searchDate                         object
 2   flightDate                         object
 3   startingAirport                    object
 4   destinationAirport                 object
 5   travelDuration                     object
 6   isBasicEconomy                     bool
 7   isRefundable                       bool
 8   isNonStop                          bool
 9   totalFare                          float64
 10  totalTravelDistance                float64
 11  segmentsDepartureTimeEpochSeconds  object
 12  segmentsDepartureTimeRaw           object
 13  segmentsArrivalTimeEpochSeconds    object
 14  segmentsArrivalTimeRaw             object
 15  segmentsArrivalAirportCode         object
 16  segmentsDepartureAirportCode       object
 17  segmentsAirlineName                object
 18  segmentsAirlineCode                object
 19  segmentsEquipmentDescription       object
 20  segmentsDurationInSeconds          object
 21  segmentsDistance                   object
 22  segmentsCabinCode                  object
dtypes: bool(3), float64(2), object(18)
memory usage: 2.1+ GB

In [9]:
airport_df.isna().sum()

legId                                     0
searchDate                                0
flightDate                                0
startingAirport                           0
destinationAirport                        0
travelDuration                            0
isBasicEconomy                            0
isRefundable                              0
isNonStop                                 0
totalFare                                 0
totalTravelDistance                  959619
segmentsDepartureTimeEpochSeconds         0
segmentsDepartureTimeRaw                  0
segmentsArrivalTimeEpochSeconds           0
segmentsArrivalTimeRaw                    0
segmentsArrivalAirportCode                0
segmentsDepartureAirportCode              0
segmentsAirlineName                       0
segmentsAirlineCode                       0
segmentsEquipmentDescription         262676
segmentsDurationInSeconds                 0
segmentsDistance                     126985
segmentsCabinCode                         0
dtype: int64

In [ ]:
import pandas as pd

def calculate_average_distances(airport_df):
    """
    Calculates the average distance between unique origin and destination airports.

    Args:
        airport_df: A pandas DataFrame with 'Origin', 'Destination', and 'Distance' columns.

    Returns:
        A pandas DataFrame with unique origin and destination airports and their average distance.
    """
    average_distances = airport_df.groupby(['startingAirport', 'destinationAirport'])['totalTravelDistance'].mean().reset_index()

    return average_distances

In [ ]:
average_distances_df = calculate_average_distances(airport_df)
print(average_distances_df)

    startingAirport destinationAirport  totalTravelDistance
0               ATL                BOS           998.032995
1               ATL                CLT           662.624730
2               ATL                DEN          1546.128489
3               ATL                DFW           907.045841
4               ATL                DTW           973.100301
5               ATL                EWR           828.117167
6               ATL                IAD           621.642341
7               ATL                JFK           962.933895
8               ATL                LAX          2086.698655
9               ATL                LGA           869.946287
10              ATL                MIA          1146.822334
11              ATL                OAK          2422.447664
12              ATL                ORD           963.911324
13              ATL                PHL           872.197084
14              ATL                SFO          2480.410744
15              BOS                ATL          1022.433277
16              BOS                CLT           780.901729
17              BOS                DEN          1906.948671
18              BOS                DFW          1643.161254
19              BOS                DTW           764.009967
20              BOS                EWR           539.270775
21              BOS                IAD           683.665775
22              BOS                JFK           239.053281
23              BOS                LAX          2701.115332
24              BOS                LGA           400.962878
25              BOS                MIA          1303.885443
26              BOS                OAK          3024.739342
27              BOS                ORD           901.905625
28              BOS                PHL           307.862851
29              BOS                SFO          2810.698748
30              CLT                ATL           687.493178
31              CLT                BOS           768.918526
32              CLT                DEN          1665.863354
33              CLT                DFW          1188.518141
34              CLT                DTW           846.271678
35              CLT                EWR           739.528487
36              CLT                IAD           555.060110
37              CLT                JFK           719.370346
38              CLT                LAX          2410.611754
39              CLT                LGA           653.995121
40              CLT                MIA           999.661151
41              CLT                OAK          2590.631698
42              CLT                ORD           958.019099
43              CLT                PHL           783.560531
44              CLT                SFO          2668.887974
45              DEN                ATL          1555.597437
46              DEN                BOS          1916.617374
47              DEN                CLT          1675.370535
48              DEN                DFW           999.619345
49              DEN                DTW          1566.599375
50              DEN                EWR          1826.871336
51              DEN                IAD          1689.050736
52              DEN                JFK          1972.285262
53              DEN                LAX          1042.640825
54              DEN                LGA          1783.045840
55              DEN                MIA          2086.934296
56              DEN                OAK          1343.065038
57              DEN                ORD          1235.222705
58              DEN                PHL          1856.073314
59              DEN                SFO          1168.848085
60              DFW                ATL           943.125849
61              DFW                BOS          1616.195688
62              DFW                CLT          1173.485869
63              DFW                DEN          1020.551995
64              DFW                DTW          1295.630639
65              DFW                EWR          1465.114842
66              DFW                IAD          1340.628958
67              DFW                JFK          1505.494012
68              DFW                LAX          1424.146323
69              DFW                LGA          1465.395053
70              DFW                MIA          1339.408543
71              DFW                OAK          1849.622985
72              DFW                ORD          1099.045163
73              DFW                PHL          1481.114031
74              DFW                SFO          1668.825115
75              DTW                ATL           979.135721
76              DTW                BOS           757.436946
77              DTW                CLT           851.546494
78              DTW                DEN          1489.455412
79              DTW                DFW          1264.021993
80              DTW                EWR           721.618292
81              DTW                IAD           593.774971
82              DTW                JFK           753.170156
83              DTW                LAX          2316.153872
84              DTW                LGA           674.838014
85              DTW                MIA          1447.017623
86              DTW                OAK          2424.441330
87              DTW                ORD           473.601038
88              DTW                PHL           766.860529
89              DTW                SFO          2449.370988
90              EWR                ATL           824.184916
91              EWR                BOS           409.204229
92              EWR                CLT           754.921066
93              EWR                DEN          1797.305442
94              EWR                DFW          1475.916326
95              EWR                DTW           730.981088
96              EWR                IAD           765.825177
97              EWR                LAX          2564.647148
98              EWR                LGA           185.000000
99              EWR                MIA          1244.717352
100             EWR                OAK          2901.031978
101             EWR                ORD           801.141403
102             EWR                PHL           973.844160
103             EWR                SFO          2672.148685
104             IAD                ATL           608.159087
105             IAD                BOS           705.915577
106             IAD                CLT           571.797580
107             IAD                DEN          1697.949139
108             IAD                DFW          1361.001270
109             IAD                DTW           614.919671
110             IAD                EWR           755.875711
111             IAD                JFK           694.070399
112             IAD                LAX          2483.741062
113             IAD                LGA           794.450809
114             IAD                MIA          1194.781090
115             IAD                OAK          2827.242849
116             IAD                ORD           829.149631
117             IAD                PHL           790.141032
118             IAD                SFO          2619.461634
119             JFK                ATL           956.159021
120             JFK                BOS           242.370472
121             JFK                CLT           715.839815
122             JFK                DEN          1968.338507
123             JFK                DFW          1548.481508
124             JFK                DTW           709.563390
125             JFK                IAD           692.624904
126             JFK                LAX          2595.339606
127             JFK                MIA          1169.808937
128             JFK                OAK          2861.984860
129             JFK                ORD           964.275647
130             JFK                PHL           690.760481
131             JFK                SFO          2648.009820
132             LAX                ATL          2128.569898
133             LAX                BOS          2730.349077
134             LAX                CLT          2397.041800
135             LAX                DEN          1115.390925
136             LAX                DFW          1423.997083
137             LAX                DTW          2303.988239
138             LAX                EWR          2588.343739
139             LAX                IAD          2488.639044
140             LAX                JFK          2673.590452
141             LAX                LGA          2652.794984
142             LAX                MIA          2616.803802
143             LAX                OAK          1282.639563
144             LAX                ORD          2008.111878
145             LAX                PHL          2580.145085
146             LAX                SFO           443.360280
147             LGA                ATL           876.247292
148             LGA                BOS           357.969841
149             LGA                CLT           655.209663
150             LGA                DEN          1788.063442
151             LGA                DFW          1464.598985
152             LGA                DTW           656.937744
153             LGA                IAD           781.897926
154             LGA                LAX          2610.110641
155             LGA                MIA          1247.214757
156             LGA                OAK          2931.228271
157             LGA                ORD           753.142725
158             LGA                PHL          1068.936809
159             LGA                SFO          2785.523336
160             MIA                ATL          1140.451469
161             MIA                BOS          1302.065913
162             MIA                CLT          1033.500137
163             MIA                DEN          2051.121327
164             MIA                DFW          1359.691477
165             MIA                DTW          1431.063893
166             MIA                EWR          1254.076412
167             MIA                IAD          1181.231862
168             MIA                JFK          1159.374083
169             MIA                LAX          2495.758461
170             MIA                LGA          1265.836302
171             MIA                OAK          3010.682767
172             MIA                ORD          1508.049157
173             MIA                PHL          1238.466845
174             MIA                SFO          3027.242965
175             OAK                ATL          2470.936203
176             OAK                BOS          2994.084059
177             OAK                CLT          2688.345235
178             OAK                DEN          1328.685395
179             OAK                DFW          1927.349242
180             OAK                DTW          2442.496863
181             OAK                EWR          2886.103977
182             OAK                IAD          2790.073662
183             OAK                JFK          2832.980710
184             OAK                LAX          1284.120799
185             OAK                LGA          2988.521198
186             OAK                MIA          3120.593744
187             OAK                ORD          2177.681736
188             OAK                PHL          2843.224381
189             OAK                SFO           894.445085
190             ORD                ATL           980.419370
191             ORD                BOS           891.764732
192             ORD                CLT           967.872353
193             ORD                DEN          1146.059964
194             ORD                DFW          1078.003606
195             ORD                DTW           402.199384
196             ORD                EWR           795.881984
197             ORD                IAD           851.315355
198             ORD                JFK           932.850028
199             ORD                LAX          1990.440229
200             ORD                LGA           759.605102
201             ORD                MIA          1525.449269
202             ORD                OAK          2190.762284
203             ORD                PHL           872.963504
204             ORD                SFO          2067.443734
205             PHL                ATL           889.803715
206             PHL                BOS           404.566977
207             PHL                CLT           776.795122
208             PHL                DEN          1807.360204
209             PHL                DFW          1480.412761
210             PHL                DTW           759.808197
211             PHL                EWR           982.080189
212             PHL                IAD           893.933608
213             PHL                JFK           713.597814
214             PHL                LAX          2523.597749
215             PHL                LGA          1035.803049
216             PHL                MIA          1267.929754
217             PHL                OAK          2828.712171
218             PHL                ORD           854.255065
219             PHL                SFO          2717.510025
220             SFO                ATL          2546.512910
221             SFO                BOS          2801.836639
222             SFO                CLT          2662.089681
223             SFO                DEN          1222.786264
224             SFO                DFW          1754.688418
225             SFO                DTW          2475.865535
226             SFO                EWR          2710.981341
227             SFO                IAD          2633.384709
228             SFO                JFK          2656.580976
229             SFO                LAX           441.358242
230             SFO                LGA          2797.891610
231             SFO                MIA          3053.785949
232             SFO                OAK           852.857010
233             SFO                ORD          2082.642492
234             SFO                PHL          2729.172899

In [18]:
from statistics import mode
def extract_departure_time(time_obj):
    """Categorizes a time string into more specific time periods."""
    try:
        hour = time_obj.hour

        if 4 <= hour < 6:
            return 'Dawn'
        elif 6 <= hour < 12:
            return 'Morning'
        elif 12 <= hour < 17:
            return 'Afternoon'
        elif 17 <= hour < 20:
            return 'Evening'
        else:
            return 'Night'
    except (ValueError, TypeError, IndexError):
        return 'Unknown'

from statistics import mode

def clean_cabin_type(cabin_type_str):
    """
    Cleans the cabin type string, finds the mode, and assigns a score.
    """
    if cabin_type_str:
        cabin_types = cabin_type_str.lower().split('|')

        total_score = 0
        for cabin in cabin_types:
            if cabin == 'coach':
                total_score += 1
            elif cabin == 'premium coach':
                total_score += 2
            elif cabin == 'business':
                total_score += 3
            elif cabin == 'first':
                total_score += 4


        mode_cabin = mode(cabin_types)

        return mode_cabin, total_score  # Return both mode and total score
    else:
        return 'Unknown', 0  # Return 'Unknown' and 0 if cabin_type_str is empty

def impute_distance_by_average(df):
  # Calculate average distances for each route
  average_distances = df.groupby(['startingAirport', 'destinationAirport'])['totalTravelDistance'].mean().reset_index()
  # Merge average distances back into the original DataFrame
  df = pd.merge(df, average_distances, on=['startingAirport', 'destinationAirport'], how='left', suffixes=('', '_avg'))
  # Fill missing values with the calculated averages
  df['totalTravelDistance'] = df['totalTravelDistance'].fillna(df['totalTravelDistance_avg'])
  # Drop the temporary average distance column
  df = df.drop(columns=['totalTravelDistance_avg'])
  return df




def clean_data(df):
    """
    Cleans and preprocesses a DataFrame containing flight data.

    This function performs the following cleaning and transformation steps:

    1. Cleans and standardizes airport codes in 'startingAirport' and 'destinationAirport' columns:
        - Removes leading/trailing whitespace.
        - Converts airport codes to uppercase.
        - Removes any non-alphabet characters.

    2. Extracts date components from 'flightDate' column:
        - Extracts year, month, and day into separate columns.

    3. Processes 'segmentsDepartureTimeRaw' column:
        - Extracts the first departure time if multiple times are present (separated by '|').
        - Converts the departure time to datetime objects (UTC).
        - Categorizes the departure time into time-of-day categories (Dawn, Morning, etc.).

    4. Cleans 'segmentsCabinCode' column:
        - Cleans and standardizes cabin codes.
        - Finds the mode of cabin codes if multiple codes are present.

    Args:
        df: The pandas DataFrame containing the flight data.

    Returns:
        The cleaned and preprocessed DataFrame.
    """
    cleaned_df = pd.DataFrame()
    cleaned_df['startingAirport'] = (
        df['startingAirport']
        .str.strip()
        .str.upper()
        .str.replace('[^A-Z]', '', regex=True)
    )
    # cleaned_df['startingAirport'] = cleaned_df['startingAirport'].astype(str).str.split('|').apply(lambda x: x[0])


    cleaned_df['destinationAirport'] = (
        df['destinationAirport']
        .str.strip()
        .str.upper()
        .str.replace('[^A-Z]', '', regex=True)
    )
    # cleaned_df['destinationAirport'] = cleaned_df['destinationAirport'].astype(str).str.split('|').apply(lambda x: x[0])

    cleaned_df['Departure_Year'] = pd.to_datetime(df['flightDate']).dt.year
    cleaned_df['Departure_Month'] = pd.to_datetime(df['flightDate']).dt.month
    cleaned_df['Departure_Day'] = pd.to_datetime(df['flightDate']).dt.day


    df['segmentsDepartureTimeRaw'] = df['segmentsDepartureTimeRaw'].astype(str).str.split('|').apply(lambda x: x[0])
    df['segmentsDepartureTimeRaw'] = pd.to_datetime(df['segmentsDepartureTimeRaw'], utc=True)
    cleaned_df['depatureTimeCategory'] = df['segmentsDepartureTimeRaw'].apply(extract_departure_time)

    cabin_info = df['segmentsCabinCode'].apply(clean_cabin_type)
    cleaned_df['Cabin_Type'] = [cabin[0] for cabin in cabin_info] # Extract the cabin type (mode)
    cleaned_df['Cabin_Score'] = [cabin[1] for cabin in cabin_info]

    cleaned_df['totalFare']  = df['totalFare']
    cleaned_df['totalTravelDistance'] = df['totalTravelDistance']

    cleaned_df = impute_distance_by_average(cleaned_df)

    return cleaned_df

In [19]:
Airport_df_cleaned = clean_data(airport_df)

In [20]:
Airport_df_cleaned.sample(20)

,startingAirport,destinationAirport,Departure_Year,Departure_Month,Departure_Day,depatureTimeCategory,Cabin_Type,Cabin_Score,totalFare,totalTravelDistance
11409434,ORD,BOS,2022,5,4,Afternoon,coach,2,287.60,905.000000
9021784,LGA,SFO,2022,5,15,Morning,coach,2,811.61,3060.000000
1486432,BOS,SFO,2022,5,25,Night,coach,1,378.60,2698.000000
9134434,LGA,ORD,2022,5,8,Evening,coach,1,228.60,720.000000
10675728,OAK,DEN,2022,6,9,Afternoon,coach,2,527.19,1186.000000
9656911,MIA,ORD,2022,5,9,Morning,coach,2,368.60,1824.000000
1076135,BOS,MIA,2022,5,28,Morning,coach,1,163.60,1260.000000
878084,BOS,LAX,2022,4,24,Morning,coach,2,630.60,3366.000000
4208721,DFW,DEN,2022,7,5,Night,coach,1,93.99,650.000000
5223939,EWR,ORD,2022,5,8,Night,coach,2,412.20,722.000000
8299241,LAX,EWR,2022,6,7,Night,coach,2,423.20,2465.000000
13185306,SFO,ORD,2022,5,25,Afternoon,coach,3,566.10,2214.000000
9238013,LGA,OAK,2022,6,17,Morning,coach,3,830.71,3542.000000
7337655,LAX,SFO,2022,5,27,Dawn,coach,1,278.60,339.000000
10295854,MIA,LAX,2022,6,20,Evening,coach,2,558.61,3037.000000
13413597,SFO,BOS,2022,7,2,Dawn,coach,2,751.60,2751.000000
10557230,OAK,DFW,2022,6,14,Dawn,coach,2,194.58,1927.349242
751956,ATL,ORD,2022,5,13,Night,coach,1,178.60,600.000000
13278422,SFO,PHL,2022,6,23,Evening,coach,2,721.60,2663.000000
2070622,CLT,MIA,2022,5,30,Morning,coach,2,331.70,1250.000000

In [21]:
# prompt: use the attached gpu here to train a xgb model on the Airport_df_cleaned to predict totalFare

import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Assuming Airport_df_cleaned is already defined from the previous code

# Prepare the data
X = Airport_df_cleaned.drop('totalFare', axis=1)
y = Airport_df_cleaned['totalFare']

# Convert categorical features to numerical using one-hot encoding
X = pd.get_dummies(X, columns=['startingAirport', 'destinationAirport', 'depatureTimeCategory', 'Cabin_Type'], drop_first=True)


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the XGBoost model with GPU support
# Check if GPU is available
try:
    import cudf
    import cuml
    print('GPU is available')
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)
    params = {'tree_method':'gpu_hist', 'objective':'reg:squarederror', 'eval_metric':'rmse'}
    model = xgb.train(params, dtrain, num_boost_round=100) # Adjust num_boost_round as needed
    # Make predictions
    y_pred = model.predict(dtest)

except ImportError:
    print('GPU is not available, proceeding with CPU training')
    model = xgb.XGBRegressor(objective='reg:squarederror', eval_metric='rmse', tree_method='hist') # Use 'hist' for better CPU performance
    model.fit(X_train, y_train)
    # Make predictions
    y_pred = model.predict(X_test)

# Evaluate the model
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"RMSE: {rmse}")

GPU is not available, proceeding with CPU training
RMSE: 114.12255922471805

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

# Pre Processing

In [23]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pickle
from sklearn.preprocessing import OneHotEncoder
import joblib
from scipy.stats.mstats import winsorize

In [24]:
def cyclical_encode(data, col):
    data[col + '_sin'] = np.sin(2 * np.pi * data[col]/max(data[col]))
    data[col + '_cos'] = np.cos(2 * np.pi * data[col]/max(data[col]))
    return data

def pre_procedss_airport_data(df):
  label_encoder = LabelEncoder()
  combined_airports = pd.concat([df['startingAirport'], df['destinationAirport']])
  label_encoder.fit(combined_airports)
  df['startingAirport_encoded'] = label_encoder.transform(df['startingAirport'])
  df['destinationAirport_encoded'] = label_encoder.transform(df['destinationAirport'])

  with open('airport_enoder.pkl', 'wb') as f:
    pickle.dump(label_encoder, f)



  df = cyclical_encode(df, 'Departure_Month')
  df = cyclical_encode(df, 'Departure_Day')
  df = cyclical_encode(df, 'Departure_Year')


  # Create a OneHotEncoder object
  encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
  encoder.fit(df[['depatureTimeCategory', 'Cabin_Type']])

  joblib.dump(encoder, 'onehot_encoder.joblib')
  encoded_features = encoder.transform(df[['depatureTimeCategory', 'Cabin_Type']])

  encoded_df = pd.DataFrame(encoded_features, columns=encoder.get_feature_names_out(['depatureTimeCategory', 'Cabin_Type']))

  # Concatenate the one-hot encoded features with the original DataFrame
  df = pd.concat([df, encoded_df], axis=1)

  df['totalFare'] = winsorize(df['totalFare'], limits=[0.05, 0.05])

  return df

In [25]:
Airport_df_pre_processed = pre_procedss_airport_data(Airport_df_cleaned)

Cabin_Score	totalFare	startingAirport_encoded	destinationAirport_encoded	Departure_Month_sin	Departure_Month_cos	Departure_Day_sin	Departure_Day_cos	Departure_Year_sin	Departure_Year_cos	depatureTimeCategory_Afternoon	depatureTimeCategory_Dawn	depatureTimeCategory_Evening	depatureTimeCategory_Morning	depatureTimeCategory_Night	Cabin_Type_	Cabin_Type_business	Cabin_Type_coach	Cabin_Type_first	Cabin_Type_premium coach

In [27]:
# prompt: startingAirport_encoded , destinationAirport_encoded Departure_Month_sin	Departure_Month_cos	Departure_Day_sin	Departure_Day_cos	Departure_Year_sin	Departure_Year_cos	depatureTimeCategory_Afternoon	depatureTimeCategory_Dawn	depatureTimeCategory_Evening	depatureTimeCategory_Morning	depatureTimeCategory_Night	Cabin_Type_	Cabin_Type_business	Cabin_Type_coach	Cabin_Type_first	Cabin_Type_premium coach Cabin_Score totalTravelDistance
# to train the model now use Airport_df_pre_processed

# Assuming Airport_df_pre_processed is already defined from the previous code

# Prepare the data for training
X = Airport_df_pre_processed[['Cabin_Score', 'totalTravelDistance', 'startingAirport_encoded', 'destinationAirport_encoded',
                             'Departure_Month_sin', 'Departure_Month_cos', 'Departure_Day_sin', 'Departure_Day_cos',
                             'Departure_Year_sin', 'Departure_Year_cos', 'depatureTimeCategory_Afternoon',
                             'depatureTimeCategory_Dawn', 'depatureTimeCategory_Evening', 'depatureTimeCategory_Morning',
                             'depatureTimeCategory_Night', 'Cabin_Type_business', 'Cabin_Type_coach', 'Cabin_Type_first',
                             'Cabin_Type_premium coach']]
y = Airport_df_pre_processed['totalFare']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the XGBoost model
try:
    print('GPU is available')
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)
    params = {'tree_method':'gpu_hist', 'objective':'reg:squarederror', 'eval_metric':'rmse'}
    model = xgb.train(params, dtrain, num_boost_round=100) # Adjust num_boost_round as needed
    # Make predictions
    y_pred = model.predict(dtest)
except ImportError:
    print('GPU is not available, proceeding with CPU training')
    model = xgb.XGBRegressor(objective='reg:squarederror', eval_metric='rmse', tree_method='hist') # Use 'hist' for better CPU performance
    model.fit(X_train, y_train)
    # Make predictions
    y_pred = model.predict(X_test)

# Evaluate the model
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"RMSE: {rmse}")

GPU is available

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [09:37:20] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)

RMSE: 91.56742169887842

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [09:37:25] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [28]:
# prompt: also calc r2

from sklearn.metrics import r2_score

# ... (Your existing code) ...

# After making predictions (y_pred)

# Evaluate the model
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"RMSE: {rmse}")

# Calculate R-squared
r2 = r2_score(y_test, y_pred)
print(f"R-squared: {r2}")

RMSE: 91.56742169887842
R-squared: 0.7116003438561058

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [ ]:
also r2

In [26]:
Airport_df_pre_processed.sample(40)

,startingAirport,destinationAirport,Departure_Year,Departure_Month,Departure_Day,depatureTimeCategory,Cabin_Type,Cabin_Score,totalFare,totalTravelDistance,startingAirport_encoded,destinationAirport_encoded,Departure_Month_sin,Departure_Month_cos,Departure_Day_sin,Departure_Day_cos,Departure_Year_sin,Departure_Year_cos,depatureTimeCategory_Afternoon,depatureTimeCategory_Dawn,depatureTimeCategory_Evening,depatureTimeCategory_Morning,depatureTimeCategory_Night,Cabin_Type_,Cabin_Type_business,Cabin_Type_coach,Cabin_Type_first,Cabin_Type_premium coach
1923631,CLT,DTW,2022,5,23,Morning,coach,2,348.08,846.271678,2,5,-9.749279e-01,-0.222521,-0.998717,-0.050649,-2.449294e-16,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
8780402,LGA,DTW,2022,6,3,Evening,coach,1,178.60,485.000000,10,5,-7.818315e-01,0.623490,0.571268,0.820763,-2.449294e-16,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9088792,LGA,PHL,2022,6,23,Evening,coach,2,462.61,774.000000,10,14,-7.818315e-01,0.623490,-0.998717,-0.050649,-2.449294e-16,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2857125,DEN,LAX,2022,6,20,Night,coach,2,333.61,954.000000,3,9,-7.818315e-01,0.623490,-0.790776,-0.612106,-2.449294e-16,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
5474812,EWR,LAX,2022,6,26,Afternoon,coach,2,711.60,2705.000000,6,9,-7.818315e-01,0.623490,-0.848644,0.528964,-2.449294e-16,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2067525,CLT,JFK,2022,5,24,Night,coach,1,127.10,545.000000,2,8,-9.749279e-01,-0.222521,-0.988468,0.151428,-2.449294e-16,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
11807896,PHL,DTW,2022,5,19,Morning,coach,2,406.60,582.000000,14,5,-9.749279e-01,-0.222521,-0.651372,-0.758758,-2.449294e-16,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
7437965,LAX,BOS,2022,5,26,Afternoon,coach,2,638.60,2771.000000,9,1,-9.749279e-01,-0.222521,-0.848644,0.528964,-2.449294e-16,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11121597,ORD,LAX,2022,6,10,Night,coach,1,291.60,1745.000000,13,9,-7.818315e-01,0.623490,0.897805,-0.440394,-2.449294e-16,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
12036405,PHL,LAX,2022,6,23,Afternoon,coach,2,545.20,2417.000000,14,9,-7.818315e-01,0.623490,-0.998717,-0.050649,-2.449294e-16,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7418970,LAX,LGA,2022,5,4,Afternoon,coach,2,621.60,2516.000000,9,10,-9.749279e-01,-0.222521,0.724793,0.688967,-2.449294e-16,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11423160,ORD,MIA,2022,5,25,Afternoon,coach,2,196.60,2076.000000,13,11,-9.749279e-01,-0.222521,-0.937752,0.347305,-2.449294e-16,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5141520,EWR,OAK,2022,4,26,Morning,coach,3,544.70,3310.000000,6,12,-4.338837e-01,-0.900969,-0.848644,0.528964,-2.449294e-16,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
7100152,JFK,SFO,2022,6,29,Night,coach,1,428.60,2566.000000,8,15,-7.818315e-01,0.623490,-0.394356,0.918958,-2.449294e-16,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
12881967,SFO,LGA,2022,4,30,Evening,coach,2,382.60,2848.000000,15,10,-4.338837e-01,-0.900969,-0.201299,0.979530,-2.449294e-16,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10251052,MIA,EWR,2022,5,29,Night,coach,1,198.60,1104.000000,11,6,-9.749279e-01,-0.222521,-0.394356,0.918958,-2.449294e-16,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3320138,DEN,OAK,2022,6,13,Evening,coach,2,216.58,1343.065038,3,12,-7.818315e-01,0.623490,0.485302,-0.874347,-2.449294e-16,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
12644245,SFO,EWR,2022,6,8,Night,coach,3,661.70,2884.000000,15,6,-7.818315e-01,0.623490,0.998717,-0.050649,-2.449294e-16,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2808967,DEN,SFO,2022,6,17,Afternoon,coach,2,711.60,1187.000000,3,15,-7.818315e-01,0.623490,-0.299363,-0.954139,-2.449294e-16,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2028191,CLT,DTW,2022,5,8,Night,coach,2,317.10,718.000000,2,5,-9.749279e-01,-0.222521,0.998717,-0.050649,-2.449294e-16,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
12904592,SFO,MIA,2022,6,6,Morning,coach,2,501.60,3670.000000,15,11,-7.818315e-01,0.623490,0.937752,0.347305,-2.449294e-16,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
11034636,ORD,SFO,2022,5,10,Evening,coach,2,698.60,1927.000000,13,15,-9.749279e-01,-0.222521,0.897805,-0.440394,-2.449294e-16,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8074099,LAX,BOS,2022,6,15,Afternoon,coach,2,563.61,2677.000000,9,1,-7.818315e-01,0.623490,0.101168,-0.994869,-2.449294e-16,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6755333,JFK,IAD,2022,6,17,Afternoon,coach,2,448.10,872.000000,8,7,-7.818315e-01,0.623490,-0.299363,-0.954139,-2.449294e-16,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9150688,LGA,LAX,2022,6,2,Afternoon,coach,2,332.60,2516.000000,10,9,-7.818315e-01,0.623490,0.394356,0.918958,-2.449294e-16,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7122175,LAX,PHL,2022,4,25,Night,coach,2,711.60,2886.000000,9,14,-4.338837e-01,-0.900969,-0.937752,0.347305,-2.449294e-16,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
8948881,LGA,DTW,2022,5,26,Evening,coach,1,195.60,485.000000,10,5,-9.749279e-01,-0.222521,-0.848644,0.528964,-2.449294e-16,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5936814,IAD,DTW,2022,4,28,Night,coach,1,218.60,391.000000,7,5,-4.338837e-01,-0.900969,-0.571268,0.820763,-2.449294e-16,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
5813901,EWR,IAD,2022,6,22,Evening,coach,2,330.70,872.000000,6,7,-7.818315e-01,0.623490,-0.968077,-0.250653,-2.449294e-16,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11265013,ORD,OAK,2022,6,20,Evening,coach,2,647.21,1839.000000,13,12,-7.818315e-01,0.623490,-0.790776,-0.612106,-2.449294e-16,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8949468,LGA,DTW,2022,5,27,Evening,coach,1,230.60,485.000000,10,5,-9.749279e-01,-0.222521,-0.724793,0.688967,-2.449294e-16,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3307225,DEN,ORD,2022,5,18,Evening,coach,1,298.60,903.000000,3,13,-9.749279e-01,-0.222521,-0.485302,-0.874347,-2.449294e-16,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5050236,DTW,LAX,2022,7,2,Afternoon,coach,2,452.20,2943.000000,5,9,-2.449294e-16,1.000000,0.394356,0.918958,-2.449294e-16,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9623948,MIA,DFW,2022,5,10,Evening,coach,2,137.60,1191.000000,11,4,-9.749279e-01,-0.222521,0.897805,-0.440394,-2.449294e-16,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1234734,BOS,DFW,2022,6,10,Afternoon,coach,2,247.60,1565.000000,1,4,-7.818315e-01,0.623490,0.897805,-0.440394,-2.449294e-16,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
815813,ATL,OAK,2022,7,8,Morning,coach,3,359.07,2422.447664,0,12,-2.449294e-16,1.000000,0.998717,-0.050649,-2.449294e-16,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
10621520,OAK,LGA,2022,6,29,Evening,coach,3,711.60,3115.000000,12,10,-7.818315e-01,0.623490,-0.394356,0.918958,-2.449294e-16,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8708122,LGA,OAK,2022,5,10,Evening,coach,3,572.10,2589.000000,10,12,-9.749279e-01,-0.222521,0.897805,-0.440394,-2.449294e-16,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2725866,DEN,LGA,2022,4,24,Afternoon,coach,2,549.60,2030.000000,3,10,-4.338837e-01,-0.900969,-0.988468,0.151428,-2.449294e-16,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
654114,ATL,BOS,2022,6,14,Afternoon,coach,2,118.60,998.032995,0,1,-7.818315e-01,0.623490,0.299363,-0.954139,-2.449294e-16,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0